### PR TITLE
Update fingerprint64.sql

### PR DESCRIPTION
**Pull request by rockwellw**

### CODE REVIEW

**Comment by tlint** [comment]
Hey - I just got a notification for this PR. You guys should probably remove me. Hope you are all doing well though! :)

**Comment by JacobHayes** [comment]
Hey Taylor, hope you're doing well too! Looks like you are removed from the org but are watching the repo. Maybe since this repo is public, you got automatically added as a watcher back in the day?

**Comment by JacobHayes** [comment]
@rockwellw think we can close or were the decent performance increases? If we want to keep, we'll want to add to `fingerprint64_array`.

**Comment by rockwellw** [comment]
> @rockwellw think we can close or were the decent performance increases? If we want to keep, we'll want to add to `fingerprint64_array`.

I never got around to fully using this, let's punt for now

**Pull request closed without merging**
